/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Win10
 */
import DAO.MovieDAO;
import DAO.RoomDAO;
import java.sql.*;
import DAO.ShowtimeDAO;
import entity.Movie;
import entity.Room;
import entity.Showtime;
import java.awt.HeadlessException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class ShowtimeGUI extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShowtimeGUI.class.getName());
    private final ShowtimeDAO showtimeDAO;
    private final MovieDAO movieDAO;
    private final RoomDAO roomDAO;
    private DefaultTableModel model;
    /**
     * Creates new form ShowtimeGUI
     */
    public ShowtimeGUI() {
        showtimeDAO=new ShowtimeDAO();
        movieDAO=new MovieDAO();
        roomDAO=new RoomDAO();
        initComponents();
        loadMovie();
        loadRoom();
        getTable();
        tableShowtime.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tableShowtime.getSelectedRow() != -1) {
                loadSelected();
            }
        });               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        timeField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShowtime = new javax.swing.JTable();
        MovieComboBox = new javax.swing.JComboBox<>();
        RoomComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã suất chiếu");

        jLabel2.setText("Phim");

        jLabel3.setText("Phòng");

        jLabel4.setText("Giá");

        jLabel5.setText("Ngày chiếu");

        jLabel6.setText("Giờ chiếu");

        addBtn.setText("Thêm");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Sửa");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Xóa");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        tableShowtime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã suất", "Phim", "Phòng", "Ngày chiếu", "Giờ chiếu", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableShowtime);

        MovieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MovieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(deleteBtn))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGap(69, 69, 69)
                                .addComponent(editBtn)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MovieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editBtn)
                        .addComponent(deleteBtn)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            String movieId = ((String) MovieComboBox.getSelectedItem()).split(" - ")[0];
            String roomId = ((String) RoomComboBox.getSelectedItem()).split(" - ")[0];
            
            Movie movie = movieDAO.findById(movieId);
            Room room = roomDAO.findById(roomId);
            
            if (movie == null || room == null) {
                JOptionPane.showMessageDialog(this, "Phim hoặc phòng không tồn tại!");
                return;
            }
            DateTimeFormatter formatDate = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            DateTimeFormatter formatTime = DateTimeFormatter.ofPattern("HH:MM");            
            LocalDate date = LocalDate.parse(dateField.getText().trim(), formatDate);
            LocalTime startTime = LocalTime.parse(timeField.getText().trim(), formatTime);        
            Showtime showTime = new Showtime(
                idField.getText().trim(),
                movie,
                room,
                date,    
                startTime,
                Double.valueOf(priceField.getText().trim())
            );       
            showtimeDAO.addShowtime(showTime);
            JOptionPane.showMessageDialog(this,"Thêm thành công");
            getTable();
            ClearForm();
        }catch(SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Lỗi thêm suất chiếu");           
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
    /*      int selectedRow = tableShowtime.getSelectedRow();
          if(selectedRow == -1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn suất chiếu cần sửa");
            return;
          }*/        
          try {
            String movieId = ((String) MovieComboBox.getSelectedItem()).split(" - ")[0];
            String roomId = ((String) RoomComboBox.getSelectedItem()).split(" - ")[0];
            
            Movie movie = movieDAO.findById(movieId);
            Room room = roomDAO.findById(roomId);
            
            if (movie == null || room == null) {
                JOptionPane.showMessageDialog(this, "Phim hoặc phòng không tồn tại!");
                return;
            }
            DateTimeFormatter formatDate = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            DateTimeFormatter formatTime = DateTimeFormatter.ofPattern("HH:MM");            
            LocalDate Showdate = LocalDate.parse(dateField.getText().trim(), formatDate);
            LocalTime startTime = LocalTime.parse(timeField.getText().trim(), formatTime);        
            Showtime showTime = new Showtime(
                idField.getText().trim(),
                movie,
                room,
                Showdate,    
                startTime,
                Double.valueOf(priceField.getText().trim())
            );       
            showtimeDAO.editShowtime(showTime);            
            JOptionPane.showMessageDialog(this,"Cập nhật thành công");
            getTable();
            ClearForm();
          } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Lỗi cập nhật");
          } catch(DateTimeParseException ex){
            JOptionPane.showMessageDialog(this,"Lỗi định dạng ngày giờ");
          }
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedRow = tableShowtime.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn suất chiếu cần xóa");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,"Bạn có chắc muốn xóa suất chiếu này");
        if(confirm == JOptionPane.YES_OPTION){
            String id = (String) model.getValueAt(selectedRow,0);
            try {
                showtimeDAO.deleteShowtime(id);
                JOptionPane.showMessageDialog(this,"Xóa thành công");
                getTable();
                ClearForm();
            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(this,"Lỗi xóa suất chiếu");
            }
        }        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void MovieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    private void loadMovie(){
        try {
            MovieComboBox.removeAllItems();
            List<Movie> movies = movieDAO.findAll();           
            for (Movie movie : movies) {
               if(movie.isShowing()==true){ 
                 MovieComboBox.addItem(movie.getId() + " - " + movie.getTitle());
               } 
            }
        } catch(SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this,"Lỗi"+ex.getMessage());
        }
    }

    private void loadRoom() {
        try {
            RoomComboBox.removeAllItems();
            List<Room> rooms = roomDAO.findAll();
            for (Room room : rooms) {
                RoomComboBox.addItem(room.getId() + " - " + room.getName());
            }
        } catch(SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this,"Lỗi"+ex.getMessage());
        }
    }
    private void getTable() {
        try {         
            model = (DefaultTableModel) tableShowtime.getModel();
            model.setRowCount(0);
            List<Showtime> showTimes = showtimeDAO.getAllShowtimes();
            DateTimeFormatter formatDate = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            DateTimeFormatter formatTime = DateTimeFormatter.ofPattern("HH:mm");
            for (Showtime st : showTimes) {
                model.addRow(new Object[]{
                    st.getId(),
                    st.getMovie().getTitle(),
                    st.getRoom().getName(),
                    st.getDate().format(formatDate),
                    st.getStart_time().format(formatTime)+"-"+st.getEnd_time().format(formatTime),
                    st.getShow_price()                   
                });
            }                       
        } catch(SQLException | ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this,"Lỗi"+ex.getMessage());
        }
    }
    private void loadSelected(){
        int selectedRow = tableShowtime.getSelectedRow();
        if (selectedRow != -1) {
            idField.setText((String) model.getValueAt(selectedRow, 0));         
            dateField.setText((String) model.getValueAt(selectedRow, 3));
            String time=((String) model.getValueAt(selectedRow, 4)).split("-")[0];
            timeField.setText(time);
            priceField.setText(String.valueOf(model.getValueAt(selectedRow,5)));
            try {
                Showtime show = showtimeDAO.getShowtimeById(idField.getText());
                if (show != null) {         
                    MovieComboBox.setSelectedItem(show.getMovie().getId() + " - " + show.getMovie().getTitle());
                    RoomComboBox.setSelectedItem(show.getRoom().getId() + " - " + show.getRoom().getName());
                }
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }      
    }    
    private void ClearForm(){
           idField.setText("");
           priceField.setText("");
           dateField.setText("");
           timeField.setText("");
           MovieComboBox.setSelectedIndex(0);
           RoomComboBox.setSelectedIndex(0);
           tableShowtime.clearSelection();
    }
                        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowtimeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ShowtimeGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MovieComboBox;
    private javax.swing.JComboBox<String> RoomComboBox;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField dateField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField priceField;
    private javax.swing.JTable tableShowtime;
    private javax.swing.JTextField timeField;
    // End of variables declaration//GEN-END:variables
}
